FICHERO=""   
# EN LA VARIABLE FICHERO DEBES PONER LA RUTA RELATIVA DE TU BASE DE DATOS, POR EJEMPLO EN NUESTRO PROGRAMA INICIAL LA RUTA ERA: 
"crypto/data/base.db" #PARA QUE FUNCIONE CON ESTA RUTA, POR FAVOR CREA UNA CARPETA DENTRO DE LA CARPETA crypto, y dentro crea una base de datos con sql3little llamada: base.db



#TAMBIEN NECESITARAS CREAR UNA SECRET_KEY Y METERLA EN LA VARIABLE DEL MISMO NOMBRE, ASI COMO UNA APIKEY que sera proporcionada al hacerte una cuenta en coinmarketap 
SECRET_KEY=""

apikey=""
